CREATE TABLE IF NOT EXISTS `histories` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `logname` VARCHAR(50),
    `device_group` VARCHAR(50),
    `name` VARCHAR(100),
    `target_id` INT,
    `index_id` INT,
    `status` VARCHAR(20),
    `lost` VARCHAR(10),
    `lost_num` INT DEFAULT 0,
    `date` VARCHAR(10),
    `time` VARCHAR(8),
    `date_time` VARCHAR(19),
    `timestamp` BIGINT,
    `period` VARCHAR(20),
    `unit` INT DEFAULT 1,
    `response_time` BIGINT DEFAULT 0,
    `data_count` BIGINT DEFAULT 0,
    `error_msg` TEXT,
    `error_code` VARCHAR(50),
    `metadata` JSON,
    `created_at` INT UNSIGNED,
    `updated_at` INT UNSIGNED,
    `deleted_at` INT,
    INDEX `idx_histories_logname` (`logname`),
    INDEX `idx_histories_device_group` (`device_group`),
    INDEX `idx_histories_name` (`name`),
    INDEX `idx_histories_date` (`date`),
    INDEX `idx_histories_time` (`time`),
    INDEX `idx_histories_date_time` (`date_time`),
    INDEX `idx_histories_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `history_archives` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `logname` VARCHAR(50),
    `device_group` VARCHAR(50),
    `name` VARCHAR(100),
    `target_id` INT,
    `index_id` INT,
    `status` VARCHAR(20),
    `lost` VARCHAR(10),
    `lost_num` INT DEFAULT 0,
    `date` VARCHAR(10),
    `time` VARCHAR(8),
    `date_time` VARCHAR(19),
    `timestamp` BIGINT,
    `period` VARCHAR(20),
    `unit` INT DEFAULT 1,
    `response_time` BIGINT DEFAULT 0,
    `data_count` BIGINT DEFAULT 0,
    `error_msg` TEXT,
    `error_code` VARCHAR(50),
    `metadata` JSON,
    `created_at` INT UNSIGNED,
    `updated_at` INT UNSIGNED,
    `deleted_at` INT,
    INDEX `idx_history_archives_logname` (`logname`),
    INDEX `idx_history_archives_device_group` (`device_group`),
    INDEX `idx_history_archives_name` (`name`),
    INDEX `idx_history_archives_date` (`date`),
    INDEX `idx_history_archives_timestamp` (`timestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `history_daily_stats` (
    `date` VARCHAR(10) NOT NULL,
    `logname` VARCHAR(50) NOT NULL,
    `device_group` VARCHAR(50) NOT NULL,
    `total_checks` BIGINT DEFAULT 0,
    `online_count` BIGINT DEFAULT 0,
    `offline_count` BIGINT DEFAULT 0,
    `warning_count` BIGINT DEFAULT 0,
    `error_count` BIGINT DEFAULT 0,
    `uptime_rate` DECIMAL(5,2) DEFAULT 0.00,
    `avg_response_time` DECIMAL(10,2) DEFAULT 0.00,
    `created_at` INT UNSIGNED,
    `updated_at` INT UNSIGNED,
    `deleted_at` INT,
    PRIMARY KEY (`date`, `logname`, `device_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `mail_histories` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `date` VARCHAR(50),
    `time` VARCHAR(50),
    `logname` VARCHAR(50),
    `sended` TINYINT(1),
    `created_at` INT UNSIGNED,
    `updated_at` INT UNSIGNED,
    `deleted_at` INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `alert_histories` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `logname` VARCHAR(50),
    `device_group` VARCHAR(50),
    `device_name` VARCHAR(100),
    `alert_type` VARCHAR(20),
    `severity` VARCHAR(10),
    `message` TEXT,
    `status` VARCHAR(20),
    `resolved_at` BIGINT,
    `resolved_by` VARCHAR(100),
    `created_at` INT UNSIGNED,
    `updated_at` INT UNSIGNED,
    `deleted_at` INT,
    INDEX `idx_alert_histories_logname` (`logname`),
    INDEX `idx_alert_histories_device_group` (`device_group`),
    INDEX `idx_alert_histories_device_name` (`device_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
