CREATE TABLE IF NOT EXISTS `elasticsearch_monitors` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `host` VARCHAR(255) NOT NULL,
    `port` INT NOT NULL DEFAULT 9200,
    `username` VARCHAR(100),
    `password` VARCHAR(255),
    `enable_auth` TINYINT(1) DEFAULT 0,
    `check_type` VARCHAR(100) DEFAULT 'health,performance',
    `interval` INT NOT NULL DEFAULT 60,
    `enable_monitor` TINYINT(1) DEFAULT 1,
    `receivers` JSON,
    `subject` VARCHAR(255),
    `description` TEXT,
    `es_connection_id` INT,
    `cpu_usage_high` DECIMAL(5,2),
    `cpu_usage_critical` DECIMAL(5,2),
    `memory_usage_high` DECIMAL(5,2),
    `memory_usage_critical` DECIMAL(5,2),
    `disk_usage_high` DECIMAL(5,2),
    `disk_usage_critical` DECIMAL(5,2),
    `response_time_high` BIGINT,
    `response_time_critical` BIGINT,
    `unassigned_shards_threshold` INT,
    `alert_threshold` JSON,
    `alert_dedupe_window` INT DEFAULT 300,
    `created_at` INT UNSIGNED,
    `updated_at` INT UNSIGNED,
    `deleted_at` INT,
    INDEX `idx_elasticsearch_monitors_es_connection_id` (`es_connection_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
